### ISSUE TITLE
INI file saves, Python output script doesn't.

### ISSUE THREAD

**Issue by CaliTarheel** [MegalexMaster/ExoPlaSim-InCon#2]
I tried using the script to produce a script to run ExoPlaSim and run into the problem where I can create the INI output, but when I try to save the .py file (tried with different locations)

this is the error message that came up in Spyder:
Inputs gathered...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\rider\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\rider\HAR Dropbox\Stephen Rider\ExoPlaSim-InCon-0.20.1\ExoPlaSim-InCon-0.20.1\EPS-IC.py", line 421, in save_file
    shutil.copyfile(param[62], lnd_path)
  File "C:\Users\rider\anaconda3\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by OstimeusAlex** [comment]
I believe you have checked the "Image/SRA toggle", which implies you have SRA files to use, but have not filled in at least the Land SRA parameter. Either fill in those boxes with the relevant paths, or have the Image/SRA toggle unchecked.

**Comment by OstimeusAlex** [comment]
Closed due to inactivity.
