### ISSUE TITLE
Failure To Launch on Virtual Machine

### ISSUE THREAD

**Issue by EMorelock** [MegalexMaster/ExoPlaSim-InCon#3]
Hello,

Previously I've used EPS-IC on openSUSE without issue. I am now trying to run the tool through virtual machine on Windows, however, I'm having issues getting the application to launch successfully. When attempting to launch, I receive the following:

EMorelock@Morelock:~> python3 EPS-IC.py
Traceback (most recent call last):
  File "EPS-IC.py", line 875, in <module>
    window = Tk()# Start the application
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

I'm not extraordinarily tech savvy, so detailed instructions on how best to solve the issue are very much appreciated. Thanks.

**Comment by OstimeusAlex** [comment]
Sorry for the late response, I have updated the program to have hopefully resolved this issue, keeping this issue open in case error persists.
